#!/usr/bin/env node
// appgen/generate.js — deterministic SolutionSpec → runnable dashboard-portal repo.
//
//   node appgen/generate.js <solution.json> [outDir]
//
// Emits a Tier-1 repo that runs locally (`npm install && npm run dev`): a
// React+Vite+TS frontend whose layout is DRIVEN BY the spec (pages/widgets +
// theme tokens), a zero-dep Node BFF that brokers the browser ↔ the pinned
// Bedrock agent, plus a CLAUDE.md listing the bounded-fill tasks for Claude Code.
//
// Principle (locked): AgentEye emits the deterministic SKELETON; Claude Code
// fills the bounded slots. Same spec → byte-identical scaffold.

'use strict';

const fs   = require('fs');
const path = require('path');

// ── helpers ──────────────────────────────────────────────────────────────────
const pascal = s => String(s || '').replace(/[^a-zA-Z0-9]+/g, ' ').split(' ').filter(Boolean).map(w => w[0].toUpperCase() + w.slice(1)).join('');
const WIDGET_COMPONENT = { kpi: 'KpiCards', chart: 'TrendChart', table: 'DataTable', 'agent-chat': 'AgentChat' };

function buildFiles(sol) {
  const app = sol.app || {};
  const theme = app.theme || {};
  const tokens = theme.tokens || {};
  const pages = app.pages || [];
  const widgets = app.widgets || [];
  const widgetById = Object.fromEntries(widgets.map(w => [w.id, w]));
  const primaryAgent = (sol.agents || []).find(a => a.role === 'primary') || (sol.agents || [])[0] || null;
  const font = theme.fontFamily || 'Segoe UI, Roboto, Helvetica, Arial, sans-serif';

  // widget types actually used across pages → which components we must emit
  const usedTypes = new Set();
  pages.forEach(p => (p.widgets || []).forEach(id => { const w = widgetById[id]; if (w) usedTypes.add(w.type); }));

  const F = {};

  // ── package.json ──
  F['package.json'] = JSON.stringify({
    name: sol.slug || 'portal', private: true, version: '0.1.0', type: 'module',
    scripts: {
      dev: 'node scripts/dev.mjs',
      'dev:web': 'vite',
      'dev:bff': 'node bff/server.mjs',
      build: 'tsc -b && vite build',
      preview: 'vite preview',
    },
    dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
    devDependencies: {
      '@types/react': '^18.3.3', '@types/react-dom': '^18.3.0',
      '@vitejs/plugin-react': '^4.3.1', typescript: '^5.5.4', vite: '^5.4.2',
    },
    optionalDependencies: { '@aws-sdk/client-bedrock-agent-runtime': '^3.600.0' },
  }, null, 2) + '\n';

  // ── tsconfig ──
  F['tsconfig.json'] = JSON.stringify({
    compilerOptions: {
      target: 'ES2020', useDefineForClassFields: true, lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext', skipLibCheck: true, moduleResolution: 'bundler', resolveJsonModule: true,
      isolatedModules: true, noEmit: true, jsx: 'react-jsx', strict: true,
    },
    include: ['src'],
  }, null, 2) + '\n';

  // ── vite config (proxies /api → BFF) ──
  F['vite.config.ts'] = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// Generated by AgentEye. The dev server proxies /api to the local BFF so the
// browser never talks to AWS directly — the BFF brokers the agent call.
export default defineConfig({
  plugins: [react()],
  server: { port: 5173, proxy: { '/api': 'http://localhost:8788' } },
});
`;

  // ── dev orchestrator: run BFF + web together, zero extra deps ──
  F['scripts/dev.mjs'] = `import { spawn } from 'node:child_process';
const run = (cmd, args) => spawn(cmd, args, { stdio: 'inherit', shell: process.platform === 'win32' });
run('node', ['bff/server.mjs']);
run('npx', ['vite']);
`;

  F['index.html'] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${sol.name || 'Portal'}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

  // ── theme tokens → CSS custom properties (re-brand = swap these values) ──
  F['src/theme.css'] = `:root {
  --primary: ${tokens.primary || '#A000FF'};
  --accent:  ${tokens.accent  || '#C1A3FF'};
  --surface: ${tokens.surface || '#FFFFFF'};
  --ink:     ${tokens.ink     || '#000000'};
  --muted:   ${tokens.muted   || '#6B6B6B'};
  --line: #e6e6e6;
  --wash: #f5f5f6;
}
* { box-sizing: border-box; }
body { margin: 0; font-family: ${font}; color: var(--ink); background: var(--wash); }
.app { display: flex; min-height: 100vh; }
.nav { width: 200px; background: var(--surface); border-right: 1px solid var(--line); padding: 14px 10px; }
.nav h1 { font-size: 15px; margin: 6px 8px 16px; }
.navitem { padding: 8px 10px; border-radius: 6px; font-size: 13px; cursor: pointer; }
.navitem.active { background: var(--primary); color: #fff; font-weight: 600; }
.main { flex: 1; display: flex; flex-direction: column; }
.topbar { display: flex; align-items: center; gap: 12px; padding: 12px 18px; border-bottom: 2px solid var(--ink); background: var(--surface); }
.topbar .env { border: 1px solid var(--primary); color: var(--primary); font-size: 11px; font-weight: 700; padding: 3px 10px; border-radius: 20px; }
.spacer { flex: 1; }
.content { display: flex; flex: 1; }
.canvas { flex: 1; padding: 18px; }
.grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.panel { border: 1px solid var(--line); border-radius: 8px; background: var(--surface); padding: 12px; }
.kpi .v { font-size: 24px; font-weight: 700; }
.kpi .k { font-size: 11px; color: var(--muted); margin-top: 4px; }
.span2 { grid-column: span 2; } .span4 { grid-column: span 4; }
table { width: 100%; border-collapse: collapse; font-size: 12px; }
th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--line); }
th { color: var(--muted); font-size: 10px; text-transform: uppercase; }
.assistant { width: 320px; border-left: 1px solid var(--line); background: var(--surface); display: flex; flex-direction: column; }
.assistant .h { padding: 12px 14px; border-bottom: 2px solid var(--primary); font-weight: 600; }
.stream { flex: 1; padding: 14px; display: flex; flex-direction: column; gap: 10px; overflow: auto; }
.bub { max-width: 85%; padding: 8px 11px; border-radius: 12px; font-size: 13px; }
.bub.a { background: var(--wash); border: 1px solid var(--line); align-self: flex-start; }
.bub.u { background: var(--primary); color: #fff; align-self: flex-end; }
.inputrow { display: flex; gap: 8px; padding: 12px; border-top: 1px solid var(--line); }
.inputrow input { flex: 1; border: 1px solid var(--line); border-radius: 18px; padding: 8px 12px; font: inherit; }
.inputrow button { border: none; background: var(--primary); color: #fff; border-radius: 18px; padding: 0 16px; cursor: pointer; }
`;

  // ── the spec, embedded as typed config the UI reads ──
  F['src/solution.ts'] = `// Generated from the SolutionSpec — the UI layout is driven by this.\n`
    + `export const solution = ${JSON.stringify({
        name: sol.name, environments: sol.environments, identity: { provider: app.identity?.provider, roles: app.identity?.rbacRoles },
        pages, widgets, primaryAgentRef: primaryAgent ? `${primaryAgent.slug}:${primaryAgent.version}` : null,
      }, null, 2)} as const;\n`;

  F['src/main.tsx'] = `import React from 'react';
import { createRoot } from 'react-dom/client';
import './theme.css';
import App from './App';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
`;

  // ── App shell: sidebar (pages) + topbar + page render + assistant rail ──
  const hasAssistant = usedTypes.has('agent-chat');
  F['src/App.tsx'] = `import { useState } from 'react';
import { solution } from './solution';
import Page from './pages/Page';
${hasAssistant ? "import AgentChat from './components/AgentChat';" : ''}

export default function App() {
  const [active, setActive] = useState(0);
  const page = solution.pages[active];
  const env = solution.environments?.[solution.environments.length - 1] ?? 'dev';
  return (
    <div className="app">
      <nav className="nav">
        <h1>{solution.name}</h1>
        {solution.pages.map((p, i) => (
          <div key={p.id} className={'navitem' + (i === active ? ' active' : '')} onClick={() => setActive(i)}>{p.title}</div>
        ))}
      </nav>
      <div className="main">
        <div className="topbar">
          <strong>{page.title}</strong><span className="spacer" />
          <span className="env">{String(env).toUpperCase()}</span>
          <span style={{ fontSize: 12, color: 'var(--muted)' }}>{solution.identity?.provider ?? 'no-auth'}</span>
        </div>
        <div className="content">
          <div className="canvas"><Page page={page} /></div>
          ${hasAssistant ? "{page.widgets.includes('assistant') && <AgentChat agentRef={solution.primaryAgentRef} />}" : ''}
        </div>
      </div>
    </div>
  );
}
`;

  // ── Page: renders widgets by type from the spec ──
  const importLines = [...usedTypes].filter(t => t !== 'agent-chat').map(t => `import ${WIDGET_COMPONENT[t]} from '../components/${WIDGET_COMPONENT[t]}';`).join('\n');
  F['src/pages/Page.tsx'] = `import { solution } from '../solution';
${importLines}
type W = (typeof solution.widgets)[number];
const byId = Object.fromEntries(solution.widgets.map(w => [w.id, w])) as Record<string, W>;

export default function Page({ page }: { page: (typeof solution.pages)[number] }) {
  return (
    <div className="grid">
      {page.widgets.map(id => {
        const w = byId[id];
        if (!w) return null;
        switch (w.type) {
${[...usedTypes].filter(t => t !== 'agent-chat').map(t => `          case '${t}': return <${WIDGET_COMPONENT[t]} key={w.id} w={w as any} />;`).join('\n')}
          default: return null; // 'agent-chat' rendered in the side rail
        }
      })}
    </div>
  );
}
`;

  // ── widget components (skeleton; Claude Code wires real data) ──
  if (usedTypes.has('kpi')) F['src/components/KpiCards.tsx'] = `export default function KpiCards({ w }: { w: any }) {
  const metrics: string[] = w.metrics ?? ['Metric A', 'Metric B', 'Metric C', 'Metric D'];
  // TODO(claude): fetch real values from dataSourceId="${'${w.dataSourceId}'}" via the BFF.
  return (<>{metrics.map((m: string, i: number) => (
    <div className="panel kpi" key={i}><div className="v">—</div><div className="k">{m}</div></div>
  ))}</>);
}
`;
  if (usedTypes.has('chart')) F['src/components/TrendChart.tsx'] = `export default function TrendChart({ w }: { w: any }) {
  // TODO(claude): replace placeholder with a real chart (e.g. recharts) bound to ${'${w.dataSourceId}'}.
  return (<div className="panel span2"><strong>{w.title}</strong>
    <div style={{ height: 150, background: 'linear-gradient(180deg,var(--wash),#fff)', borderRadius: 6, marginTop: 10 }} />
  </div>);
}
`;
  if (usedTypes.has('table')) F['src/components/DataTable.tsx'] = `export default function DataTable({ w }: { w: any }) {
  const cols: string[] = w.columns ?? ['Col A', 'Col B'];
  // TODO(claude): page real rows from the BFF (dataSourceId="${'${w.dataSourceId}'}", pageSize=${'${w.pageSize ?? 25}'}).
  return (<div className="panel span2"><strong>{w.title}</strong>
    <table><thead><tr>{cols.map(c => <th key={c}>{c}</th>)}</tr></thead>
      <tbody>{[0,1,2,3].map(r => <tr key={r}>{cols.map(c => <td key={c}>—</td>)}</tr>)}</tbody>
    </table>
  </div>);
}
`;
  if (hasAssistant) F['src/components/AgentChat.tsx'] = `import { useState } from 'react';
type Msg = { role: 'a' | 'u'; text: string };

export default function AgentChat({ agentRef }: { agentRef: string | null }) {
  const [msgs, setMsgs] = useState<Msg[]>([{ role: 'a', text: 'Hi — how can I help?' }]);
  const [text, setText] = useState('');
  const [busy, setBusy] = useState(false);
  const [sid] = useState(() => crypto.randomUUID());

  async function send() {
    const m = text.trim(); if (!m || busy) return;
    setMsgs(x => [...x, { role: 'u', text: m }]); setText(''); setBusy(true);
    try {
      const r = await fetch('/api/agent/invoke', {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ message: m, sessionId: sid }),
      });
      const j = await r.json();
      setMsgs(x => [...x, { role: 'a', text: j.reply ?? '(no reply)' }]);
    } catch (e: any) {
      setMsgs(x => [...x, { role: 'a', text: 'Error: ' + e.message }]);
    } finally { setBusy(false); }
  }

  return (
    <aside className="assistant">
      <div className="h">Assistant <span style={{ fontSize: 10, color: 'var(--muted)' }}>{agentRef}</span></div>
      <div className="stream">{msgs.map((m, i) => <div key={i} className={'bub ' + m.role}>{m.text}</div>)}</div>
      <div className="inputrow">
        <input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Ask the assistant…" />
        <button onClick={send} disabled={busy}>{busy ? '…' : 'Send'}</button>
      </div>
    </aside>
  );
}
`;

  // ── BFF: zero-dep Node http; brokers browser ↔ Bedrock agent ──
  F['bff/server.mjs'] = `// Generated by AgentEye. Zero-dependency BFF that brokers the browser and the
// pinned Bedrock agent. Reads agent coordinates from env (injected by the IaC at
// deploy; .env locally). Propagates caller identity into the agent call.
import http from 'node:http';

const PORT = process.env.PORT || 8788;
const AGENT_ID = process.env.AGENT_ID || '';
const AGENT_ALIAS_ID = process.env.AGENT_ALIAS_ID || '';
const REGION = process.env.AWS_REGION || 'us-east-1';
const PROPAGATE_IDENTITY = ${app.identity?.propagateToAgent ? 'true' : 'false'};

function json(res, code, body) { res.writeHead(code, { 'content-type': 'application/json' }); res.end(JSON.stringify(body)); }
function readBody(req) { return new Promise(r => { let b = ''; req.on('data', c => (b += c)); req.on('end', () => r(b)); }); }

// Lazily load the AWS SDK so the BFF still runs (stubbed) without it / without creds.
async function invokeAgent({ message, sessionId, caller }) {
  if (!AGENT_ID || !AGENT_ALIAS_ID) {
    return { reply: \`[stub] Agent not configured. Echo: "\${message}". Set AGENT_ID / AGENT_ALIAS_ID to call Bedrock.\`, stub: true };
  }
  try {
    const { BedrockAgentRuntimeClient, InvokeAgentCommand } = await import('@aws-sdk/client-bedrock-agent-runtime');
    const client = new BedrockAgentRuntimeClient({ region: REGION });
    const sessionState = PROPAGATE_IDENTITY && caller ? { sessionAttributes: { callerIdentity: caller } } : undefined;
    const out = await client.send(new InvokeAgentCommand({
      agentId: AGENT_ID, agentAliasId: AGENT_ALIAS_ID, sessionId: sessionId || 'sess-' + Date.now(),
      inputText: message, sessionState,
    }));
    let reply = '';
    for await (const ev of out.completion ?? []) { if (ev.chunk?.bytes) reply += Buffer.from(ev.chunk.bytes).toString('utf8'); }
    return { reply: reply || '(empty response)' };
  } catch (e) {
    return { reply: '[error] ' + e.message, error: true };
  }
}

const server = http.createServer(async (req, res) => {
  if (req.url === '/api/health') return json(res, 200, { ok: true, agentConfigured: !!(AGENT_ID && AGENT_ALIAS_ID) });
  if (req.url === '/api/agent/invoke' && req.method === 'POST') {
    const { message, sessionId } = JSON.parse((await readBody(req)) || '{}');
    if (!message) return json(res, 400, { error: 'message required' });
    const caller = PROPAGATE_IDENTITY ? (req.headers['x-user-id'] || 'anonymous') : null; // TODO(claude): derive from verified JWT
    return json(res, 200, await invokeAgent({ message, sessionId, caller }));
  }
  json(res, 404, { error: 'not found' });
});
server.listen(PORT, () => console.log('BFF on http://localhost:' + PORT));
`;

  F['.env.example'] = `# Agent coordinates — at deploy these come from the agent CloudFormation stack outputs.
AGENT_ID=
AGENT_ALIAS_ID=
AWS_REGION=${app.enterprise?.dr?.primaryRegion || 'us-east-1'}
PORT=8788
`;

  F['.gitignore'] = `node_modules\ndist\n.env\n`;

  // ── CLAUDE.md: the bounded-fill checklist ──
  const fillTasks = [];
  if (usedTypes.has('kpi'))   fillTasks.push('Wire **KpiCards** to real metrics from the BFF (`dataSourceId`); replace the `—` placeholders.');
  if (usedTypes.has('chart')) fillTasks.push('Replace **TrendChart** placeholder with a real chart library (e.g. recharts) bound to the data source.');
  if (usedTypes.has('table')) fillTasks.push('Page real rows into **DataTable** from a BFF `/api/data/*` route with server-side paging.');
  fillTasks.push('Add BFF data routes that query `' + (app.data?.sources?.[0]?.id || 'the data source') + '` (Postgres) using the Secrets Manager ref + IAM auth.');
  fillTasks.push('Adopt the blessed component foundation (**shadcn/ui + Tailwind**) for the widgets, keeping the CSS token names in `theme.css` as the brand contract.');
  if (app.identity?.provider && app.identity.provider !== 'none') fillTasks.push('Implement **' + app.identity.provider + '** auth + JWT verification in the BFF; derive `x-user-id` from the verified token (currently trusted from the header — placeholder).');
  fillTasks.push('Add tests (unit + an integration test that mocks the agent) and wire the CI verification gate.');

  F['CLAUDE.md'] = `# ${sol.name} — generated by AgentEye

Deterministic skeleton for an **agent-powered dashboard-portal**. It runs as-is
(\`npm install && npm run dev\`) with placeholder widgets and a stubbed agent reply,
so you can see the shape immediately. Your job is to fill the bounded slots below.

## Architecture
- **Frontend** (\`src/\`): React + Vite + TS. Layout is **driven by \`src/solution.ts\`** (pages → widgets). Re-brand by editing the token values in \`src/theme.css\` — do not hardcode colors in components.
- **BFF** (\`bff/server.mjs\`): zero-dep Node server. It brokers the browser ↔ the pinned Bedrock agent (\`${primaryAgent ? primaryAgent.slug + ':' + primaryAgent.version : 'none'}\`) and is the only thing that talks to AWS. Agent coordinates come from env (\`AGENT_ID\`, \`AGENT_ALIAS_ID\`) — injected by the IaC at deploy, or \`.env\` locally.

## Run
\`\`\`bash
npm install
npm run dev          # BFF on :8788, web on :5173 (proxied /api → BFF)
\`\`\`
Without \`AGENT_ID\`/\`AGENT_ALIAS_ID\` the assistant echoes a stub reply — that's expected locally.

## Bounded-fill tasks (regeneration is ONE-TIME — this file won't be regenerated over your edits)
${fillTasks.map((t, i) => `${i + 1}. ${t}`).join('\n')}

## Provenance
- Generated by \`appgen@0.1\` from SolutionSpec \`${sol.slug}:${sol.version}\`, archetype \`${sol.archetype}\`.
- Deploys via the solution \`deploy/\` bundle (app stack ← agent stack alias ARN, threaded as a parameter — not ImportValue).
`;

  F['README.md'] = `# ${sol.name}\n\n${sol.description || ''}\n\nGenerated by AgentEye (dashboard-portal archetype). See **CLAUDE.md** for architecture and the remaining build tasks. Run with \`npm install && npm run dev\`.\n`;

  return F;
}

// Re-parse the structural invariants every generated repo must hold. Throws.
function verifyRepo(F, sol) {
  JSON.parse(F['package.json']);                 // valid package.json
  JSON.parse(F['tsconfig.json']);                // valid tsconfig
  const pages = sol.app.pages || [];
  const widgetById = Object.fromEntries((sol.app.widgets || []).map(w => [w.id, w]));
  // every widget a page references exists, and its component is emitted
  for (const p of pages) for (const id of (p.widgets || [])) {
    const w = widgetById[id];
    if (!w) throw new Error(`page "${p.id}" references unknown widget "${id}"`);
    if (w.type === 'agent-chat') { if (!F['src/components/AgentChat.tsx']) throw new Error('agent-chat used but AgentChat not emitted'); continue; }
    const comp = WIDGET_COMPONENT[w.type];
    if (!comp) throw new Error(`widget "${id}" has unknown type "${w.type}"`);
    if (!F[`src/components/${comp}.tsx`]) throw new Error(`component ${comp} for widget "${id}" not emitted`);
  }
  // an agent-powered portal should pin at least one agent
  if (!(sol.agents || []).length) throw new Error('solution pins no agents (not agent-powered)');
}

function generateApp(solOrPath, outDir) {
  const sol = typeof solOrPath === 'string' ? JSON.parse(fs.readFileSync(solOrPath, 'utf8')) : solOrPath;
  if (sol.archetype !== 'dashboard-portal') throw new Error(`unsupported archetype "${sol.archetype}" (v1 = dashboard-portal)`);
  const F = buildFiles(sol);
  verifyRepo(F, sol);
  const root = outDir || path.join(__dirname, '..', 'generated', sol.slug || 'portal');
  // One-time-scaffold: overwrite only the files we generate; never wipe the
  // directory (preserves node_modules, .env, dist, and any hand edits).
  for (const [rel, content] of Object.entries(F)) {
    const dest = path.join(root, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content);
  }
  return { root, fileCount: Object.keys(F).length };
}

function main() {
  const [solPath, outDir] = process.argv.slice(2);
  if (!solPath) { console.error('usage: node appgen/generate.js <solution.json> [outDir]'); process.exit(2); }
  const { root, fileCount } = generateApp(solPath, outDir);
  console.log(`✓ generated ${fileCount} files → ${path.relative(path.join(__dirname, '..'), root)}/`);
}

if (require.main === module) main();
module.exports = { generateApp, buildFiles, verifyRepo };
