#!/usr/bin/env node
// appgen/generate.js — deterministic SolutionSpec → runnable dashboard-portal repo.
//
//   node appgen/generate.js <solution.json> [outDir]
//
// Emits a Tier-1 repo that runs locally (`npm install && npm run dev`): a
// React+Vite+TS frontend whose layout is DRIVEN BY the spec (pages/widgets +
// theme tokens), a zero-dep Node BFF that brokers the browser ↔ the pinned
// Bedrock agent, plus a CLAUDE.md listing the bounded-fill tasks for Claude Code.
//
// Principle (locked): AgentEye emits the deterministic SKELETON; Claude Code
// fills the bounded slots. Same spec → byte-identical scaffold.

'use strict';

const fs   = require('fs');
const path = require('path');

// ── helpers ──────────────────────────────────────────────────────────────────
const pascal = s => String(s || '').replace(/[^a-zA-Z0-9]+/g, ' ').split(' ').filter(Boolean).map(w => w[0].toUpperCase() + w.slice(1)).join('');
const WIDGET_COMPONENT = { kpi: 'KpiCards', chart: 'TrendChart', table: 'DataTable', 'agent-chat': 'AgentChat' };

function buildFiles(sol) {
  const app = sol.app || {};
  const theme = app.theme || {};
  const tokens = theme.tokens || {};
  const pages = app.pages || [];
  const widgets = app.widgets || [];
  const widgetById = Object.fromEntries(widgets.map(w => [w.id, w]));
  const primaryAgent = (sol.agents || []).find(a => a.role === 'primary') || (sol.agents || [])[0] || null;
  const font = theme.fontFamily || 'Segoe UI, Roboto, Helvetica, Arial, sans-serif';

  // widget types actually used across pages → which components we must emit
  const usedTypes = new Set();
  pages.forEach(p => (p.widgets || []).forEach(id => { const w = widgetById[id]; if (w) usedTypes.add(w.type); }));

  const F = {};

  // ── package.json ──
  F['package.json'] = JSON.stringify({
    name: sol.slug || 'portal', private: true, version: '0.1.0', type: 'module',
    scripts: {
      dev: 'node scripts/dev.mjs',
      'dev:web': 'vite',
      'dev:bff': 'node bff/server.mjs',
      build: 'tsc -b && vite build',
      preview: 'vite preview',
    },
    dependencies: { react: '^18.3.1', 'react-dom': '^18.3.1' },
    devDependencies: {
      '@types/react': '^18.3.3', '@types/react-dom': '^18.3.0',
      '@vitejs/plugin-react': '^4.3.1', typescript: '^5.5.4', vite: '^5.4.2',
    },
    optionalDependencies: { '@aws-sdk/client-bedrock-agent-runtime': '^3.600.0' },
  }, null, 2) + '\n';

  // ── tsconfig ──
  F['tsconfig.json'] = JSON.stringify({
    compilerOptions: {
      target: 'ES2020', useDefineForClassFields: true, lib: ['ES2020', 'DOM', 'DOM.Iterable'],
      module: 'ESNext', skipLibCheck: true, moduleResolution: 'bundler', resolveJsonModule: true,
      isolatedModules: true, noEmit: true, jsx: 'react-jsx', strict: true,
    },
    include: ['src'],
  }, null, 2) + '\n';

  // ── vite config (proxies /api → BFF) ──
  F['vite.config.ts'] = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// Generated by AgentEye. The dev server proxies /api to the local BFF so the
// browser never talks to AWS directly — the BFF brokers the agent call.
export default defineConfig({
  plugins: [react()],
  server: { port: 5173, proxy: { '/api': 'http://localhost:8788' } },
});
`;

  // ── dev orchestrator: run BFF + web together, zero extra deps ──
  F['scripts/dev.mjs'] = `import { spawn } from 'node:child_process';
const run = (cmd, args) => spawn(cmd, args, { stdio: 'inherit', shell: process.platform === 'win32' });
run('node', ['bff/server.mjs']);
run('npx', ['vite']);
`;

  F['index.html'] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${sol.name || 'Portal'}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;

  // ── theme tokens → CSS custom properties (re-brand = swap these values) ──
  F['src/theme.css'] = `:root {
  --primary: ${tokens.primary || '#A000FF'};
  --accent:  ${tokens.accent  || '#C1A3FF'};
  --surface: ${tokens.surface || '#FFFFFF'};
  --ink:     ${tokens.ink     || '#000000'};
  --muted:   ${tokens.muted   || '#6B6B6B'};
  --line: #e6e6e6;
  --wash: #f5f5f6;
}
* { box-sizing: border-box; }
body { margin: 0; font-family: ${font}; color: var(--ink); background: var(--wash); }
.app { display: flex; min-height: 100vh; }
.nav { width: 200px; background: var(--surface); border-right: 1px solid var(--line); padding: 14px 10px; }
.nav h1 { font-size: 15px; margin: 6px 8px 16px; }
.navitem { padding: 8px 10px; border-radius: 6px; font-size: 13px; cursor: pointer; }
.navitem.active { background: var(--primary); color: #fff; font-weight: 600; }
.main { flex: 1; display: flex; flex-direction: column; }
.topbar { display: flex; align-items: center; gap: 12px; padding: 12px 18px; border-bottom: 2px solid var(--ink); background: var(--surface); }
.topbar .env { border: 1px solid var(--primary); color: var(--primary); font-size: 11px; font-weight: 700; padding: 3px 10px; border-radius: 20px; }
.spacer { flex: 1; }
.content { display: flex; flex: 1; }
.canvas { flex: 1; padding: 18px; }
.grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.panel { border: 1px solid var(--line); border-radius: 8px; background: var(--surface); padding: 12px; }
.kpi .v { font-size: 24px; font-weight: 700; }
.kpi .k { font-size: 11px; color: var(--muted); margin-top: 4px; }
.span2 { grid-column: span 2; } .span4 { grid-column: span 4; }
table { width: 100%; border-collapse: collapse; font-size: 12px; }
th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--line); }
th { color: var(--muted); font-size: 10px; text-transform: uppercase; }
.assistant { width: 320px; border-left: 1px solid var(--line); background: var(--surface); display: flex; flex-direction: column; }
.assistant .h { padding: 12px 14px; border-bottom: 2px solid var(--primary); font-weight: 600; }
.stream { flex: 1; padding: 14px; display: flex; flex-direction: column; gap: 10px; overflow: auto; }
.bub { max-width: 85%; padding: 8px 11px; border-radius: 12px; font-size: 13px; }
.bub.a { background: var(--wash); border: 1px solid var(--line); align-self: flex-start; }
.bub.u { background: var(--primary); color: #fff; align-self: flex-end; }
.inputrow { display: flex; gap: 8px; padding: 12px; border-top: 1px solid var(--line); }
.inputrow input { flex: 1; border: 1px solid var(--line); border-radius: 18px; padding: 8px 12px; font: inherit; }
.inputrow button { border: none; background: var(--primary); color: #fff; border-radius: 18px; padding: 0 16px; cursor: pointer; }
`;

  // ── the spec, embedded as typed config the UI reads ──
  F['src/solution.ts'] = `// Generated from the SolutionSpec — the UI layout is driven by this.\n`
    + `export const solution = ${JSON.stringify({
        name: sol.name, environments: sol.environments, identity: { provider: app.identity?.provider, roles: app.identity?.rbacRoles },
        pages, widgets, primaryAgentRef: primaryAgent ? `${primaryAgent.slug}:${primaryAgent.version}` : null,
      }, null, 2)} as const;\n`;

  F['src/main.tsx'] = `import React from 'react';
import { createRoot } from 'react-dom/client';
import './theme.css';
import App from './App';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
`;

  // ── App shell: sidebar (pages) + topbar + page render + assistant rail ──
  const hasAssistant = usedTypes.has('agent-chat');
  const assistantId = (widgets.find(w => w.type === 'agent-chat') || {}).id || 'assistant';
  F['src/App.tsx'] = `import { useState } from 'react';
import { solution } from './solution';
import Page from './pages/Page';
${hasAssistant ? "import AgentChat from './components/AgentChat';" : ''}

export default function App() {
  const [active, setActive] = useState(0);
  const page = solution.pages[active];
  const env = solution.environments?.[solution.environments.length - 1] ?? 'dev';
  return (
    <div className="app">
      <nav className="nav">
        <h1>{solution.name}</h1>
        {solution.pages.map((p, i) => (
          <div key={p.id} className={'navitem' + (i === active ? ' active' : '')} onClick={() => setActive(i)}>{p.title}</div>
        ))}
      </nav>
      <div className="main">
        <div className="topbar">
          <strong>{page.title}</strong><span className="spacer" />
          <span className="env">{String(env).toUpperCase()}</span>
          <span style={{ fontSize: 12, color: 'var(--muted)' }}>{solution.identity?.provider ?? 'no-auth'}</span>
        </div>
        <div className="content">
          <div className="canvas"><Page page={page} /></div>
          ${hasAssistant ? `{page.widgets.includes('${assistantId}') && <AgentChat agentRef={solution.primaryAgentRef} />}` : ''}
        </div>
      </div>
    </div>
  );
}
`;

  // ── Page: renders widgets by type from the spec ──
  const importLines = [...usedTypes].filter(t => t !== 'agent-chat').map(t => `import ${WIDGET_COMPONENT[t]} from '../components/${WIDGET_COMPONENT[t]}';`).join('\n');
  F['src/pages/Page.tsx'] = `import { solution } from '../solution';
${importLines}
type W = (typeof solution.widgets)[number];
const byId = Object.fromEntries(solution.widgets.map(w => [w.id, w])) as Record<string, W>;

export default function Page({ page }: { page: (typeof solution.pages)[number] }) {
  return (
    <div className="grid">
      {page.widgets.map(id => {
        const w = byId[id];
        if (!w) return null;
        switch (w.type) {
${[...usedTypes].filter(t => t !== 'agent-chat').map(t => `          case '${t}': return <${WIDGET_COMPONENT[t]} key={w.id} w={w as any} />;`).join('\n')}
          default: return null; // 'agent-chat' rendered in the side rail
        }
      })}
    </div>
  );
}
`;

  // ── widget components (skeleton; Claude Code wires real data) ──
  if (usedTypes.has('kpi')) F['src/components/KpiCards.tsx'] = `export default function KpiCards({ w }: { w: any }) {
  const metrics: string[] = w.metrics ?? ['Metric A', 'Metric B', 'Metric C', 'Metric D'];
  // TODO(claude): fetch real values from dataSourceId="${'${w.dataSourceId}'}" via the BFF.
  return (<>{metrics.map((m: string, i: number) => (
    <div className="panel kpi" key={i}><div className="v">—</div><div className="k">{m}</div></div>
  ))}</>);
}
`;
  if (usedTypes.has('chart')) F['src/components/TrendChart.tsx'] = `export default function TrendChart({ w }: { w: any }) {
  // TODO(claude): replace placeholder with a real chart (e.g. recharts) bound to ${'${w.dataSourceId}'}.
  return (<div className="panel span2"><strong>{w.title}</strong>
    <div style={{ height: 150, background: 'linear-gradient(180deg,var(--wash),#fff)', borderRadius: 6, marginTop: 10 }} />
  </div>);
}
`;
  if (usedTypes.has('table')) F['src/components/DataTable.tsx'] = `export default function DataTable({ w }: { w: any }) {
  const cols: string[] = w.columns ?? ['Col A', 'Col B'];
  // TODO(claude): page real rows from the BFF (dataSourceId="${'${w.dataSourceId}'}", pageSize=${'${w.pageSize ?? 25}'}).
  return (<div className="panel span2"><strong>{w.title}</strong>
    <table><thead><tr>{cols.map(c => <th key={c}>{c}</th>)}</tr></thead>
      <tbody>{[0,1,2,3].map(r => <tr key={r}>{cols.map(c => <td key={c}>—</td>)}</tr>)}</tbody>
    </table>
  </div>);
}
`;
  if (hasAssistant) F['src/components/AgentChat.tsx'] = `import { useState } from 'react';
type Msg = { role: 'a' | 'u'; text: string };

export default function AgentChat({ agentRef }: { agentRef: string | null }) {
  const [msgs, setMsgs] = useState<Msg[]>([{ role: 'a', text: 'Hi — how can I help?' }]);
  const [text, setText] = useState('');
  const [busy, setBusy] = useState(false);
  const [sid] = useState(() => crypto.randomUUID());

  async function send() {
    const m = text.trim(); if (!m || busy) return;
    setMsgs(x => [...x, { role: 'u', text: m }]); setText(''); setBusy(true);
    try {
      const r = await fetch('/api/agent/invoke', {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ message: m, sessionId: sid }),
      });
      const j = await r.json();
      setMsgs(x => [...x, { role: 'a', text: j.reply ?? '(no reply)' }]);
    } catch (e: any) {
      setMsgs(x => [...x, { role: 'a', text: 'Error: ' + e.message }]);
    } finally { setBusy(false); }
  }

  return (
    <aside className="assistant">
      <div className="h">Assistant <span style={{ fontSize: 10, color: 'var(--muted)' }}>{agentRef}</span></div>
      <div className="stream">{msgs.map((m, i) => <div key={i} className={'bub ' + m.role}>{m.text}</div>)}</div>
      <div className="inputrow">
        <input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Ask the assistant…" />
        <button onClick={send} disabled={busy}>{busy ? '…' : 'Send'}</button>
      </div>
    </aside>
  );
}
`;

  // ── BFF: zero-dep Node http; brokers browser ↔ Bedrock agent ──
  F['bff/server.mjs'] = `// Generated by AgentEye. Zero-dependency BFF that brokers the browser and the
// pinned Bedrock agent. Reads agent coordinates from env (injected by the IaC at
// deploy; .env locally). Propagates caller identity into the agent call.
import http from 'node:http';

const PORT = process.env.PORT || 8788;
const AGENT_ID = process.env.AGENT_ID || '';
const AGENT_ALIAS_ID = process.env.AGENT_ALIAS_ID || '';
const REGION = process.env.AWS_REGION || 'us-east-1';
const PROPAGATE_IDENTITY = ${app.identity?.propagateToAgent ? 'true' : 'false'};

function json(res, code, body) { res.writeHead(code, { 'content-type': 'application/json' }); res.end(JSON.stringify(body)); }
function readBody(req) { return new Promise(r => { let b = ''; req.on('data', c => (b += c)); req.on('end', () => r(b)); }); }

// Lazily load the AWS SDK so the BFF still runs (stubbed) without it / without creds.
async function invokeAgent({ message, sessionId, caller }) {
  if (!AGENT_ID || !AGENT_ALIAS_ID) {
    return { reply: \`[stub] Agent not configured. Echo: "\${message}". Set AGENT_ID / AGENT_ALIAS_ID to call Bedrock.\`, stub: true };
  }
  try {
    const { BedrockAgentRuntimeClient, InvokeAgentCommand } = await import('@aws-sdk/client-bedrock-agent-runtime');
    const client = new BedrockAgentRuntimeClient({ region: REGION });
    const sessionState = PROPAGATE_IDENTITY && caller ? { sessionAttributes: { callerIdentity: caller } } : undefined;
    const out = await client.send(new InvokeAgentCommand({
      agentId: AGENT_ID, agentAliasId: AGENT_ALIAS_ID, sessionId: sessionId || 'sess-' + Date.now(),
      inputText: message, sessionState,
    }));
    let reply = '';
    for await (const ev of out.completion ?? []) { if (ev.chunk?.bytes) reply += Buffer.from(ev.chunk.bytes).toString('utf8'); }
    return { reply: reply || '(empty response)' };
  } catch (e) {
    return { reply: '[error] ' + e.message, error: true };
  }
}

const server = http.createServer(async (req, res) => {
  if (req.url === '/api/health') return json(res, 200, { ok: true, agentConfigured: !!(AGENT_ID && AGENT_ALIAS_ID) });
  if (req.url === '/api/agent/invoke' && req.method === 'POST') {
    const { message, sessionId } = JSON.parse((await readBody(req)) || '{}');
    if (!message) return json(res, 400, { error: 'message required' });
    const caller = PROPAGATE_IDENTITY ? (req.headers['x-user-id'] || 'anonymous') : null; // TODO(claude): derive from verified JWT
    return json(res, 200, await invokeAgent({ message, sessionId, caller }));
  }
  json(res, 404, { error: 'not found' });
});
server.listen(PORT, () => console.log('BFF on http://localhost:' + PORT));
`;

  F['.env.example'] = `# Agent coordinates — at deploy these come from the agent CloudFormation stack outputs.
AGENT_ID=
AGENT_ALIAS_ID=
AWS_REGION=${app.enterprise?.dr?.primaryRegion || 'us-east-1'}
PORT=8788
`;

  F['.gitignore'] = `node_modules\ndist\n.env\n`;

  // ── CLAUDE.md: the bounded-fill checklist ──
  const fillTasks = [];
  if (usedTypes.has('kpi'))   fillTasks.push('Wire **KpiCards** to real metrics from the BFF (`dataSourceId`); replace the `—` placeholders.');
  if (usedTypes.has('chart')) fillTasks.push('Replace **TrendChart** placeholder with a real chart library (e.g. recharts) bound to the data source.');
  if (usedTypes.has('table')) fillTasks.push('Page real rows into **DataTable** from a BFF `/api/data/*` route with server-side paging.');
  fillTasks.push('Add BFF data routes that query `' + (app.data?.sources?.[0]?.id || 'the data source') + '` (Postgres) using the Secrets Manager ref + IAM auth.');
  fillTasks.push('Adopt the blessed component foundation (**shadcn/ui + Tailwind**) for the widgets, keeping the CSS token names in `theme.css` as the brand contract.');
  if (app.identity?.provider && app.identity.provider !== 'none') fillTasks.push('Implement **' + app.identity.provider + '** auth + JWT verification in the BFF; derive `x-user-id` from the verified token (currently trusted from the header — placeholder).');
  fillTasks.push('Add tests (unit + an integration test that mocks the agent) and wire the CI verification gate.');

  F['CLAUDE.md'] = `# ${sol.name} — generated by AgentEye

Deterministic skeleton for an **agent-powered dashboard-portal**. It runs as-is
(\`npm install && npm run dev\`) with placeholder widgets and a stubbed agent reply,
so you can see the shape immediately. Your job is to fill the bounded slots below.

## Architecture
- **Frontend** (\`src/\`): React + Vite + TS. Layout is **driven by \`src/solution.ts\`** (pages → widgets). Re-brand by editing the token values in \`src/theme.css\` — do not hardcode colors in components.
- **BFF** (\`bff/server.mjs\`): zero-dep Node server. It brokers the browser ↔ the pinned Bedrock agent (\`${primaryAgent ? primaryAgent.slug + ':' + primaryAgent.version : 'none'}\`) and is the only thing that talks to AWS. Agent coordinates come from env (\`AGENT_ID\`, \`AGENT_ALIAS_ID\`) — injected by the IaC at deploy, or \`.env\` locally.

## Run
\`\`\`bash
npm install
npm run dev          # BFF on :8788, web on :5173 (proxied /api → BFF)
\`\`\`
Without \`AGENT_ID\`/\`AGENT_ALIAS_ID\` the assistant echoes a stub reply — that's expected locally.

## Bounded-fill tasks (regeneration is ONE-TIME — this file won't be regenerated over your edits)
${fillTasks.map((t, i) => `${i + 1}. ${t}`).join('\n')}

## Operations & handover
The following enterprise deployment artifacts are emitted alongside the application skeleton.
Reference them for day-two operations and when handing over to client engineering teams.

- **\`solution.manifest.json\`** — canonical spec spine: identity, dependency pins, stack choices, quality skills, lifecycle commands. Source of truth for what was generated and why.
- **\`Makefile\`** — lifecycle verbs: \`make setup\`, \`make build\`, \`make verify\`, \`make deploy ENV=dev|stage|prod\`, \`make smoke\`, \`make teardown\`. Start here for all env operations.
- **\`docs/ARCHITECTURE.md\`** — tier map, agent dependency table, data flow, trust boundaries.
- **\`docs/RUNBOOK.md\`** — Makefile verb reference, deploy order (agent stacks → app stack), rollback, observability, common failures.
- **\`docs/ENVIRONMENT-SETUP.md\`** — prerequisites, secrets layout, per-env parameter files, landing zone constraints checklist.
- **\`docs/THREAT-MODEL.md\`** — data classes, STRIDE-lite bullets, identity posture, residency and guardrail notes.
- **\`docs/COST.md\`** — resource cost map, cost-allocation tag wiring, agent model invoke cost note.
- **\`docs/adr/0001-blessed-stack.md\`** — Architecture Decision Record for the golden-path stack and IaC engine choice.
- **\`.github/workflows/deliver.yml\`** — CI/CD pipeline: build → verify → scan → deploy-dev → deploy-stage → sign-off gate → deploy-prod → smoke.
- **\`.claude/skills/README.md\`** — curated, vendored Claude Code engineering skills pre-selected for this solution; listed in \`solution.manifest.json#quality.skills\`.
- **\`deploy/parameters/\`** — per-environment parameter templates (\`dev.json\`, \`stage.json\`, \`prod.json\`) for the deploy bundle.

## Provenance
- Generated by \`appgen@0.1\` from SolutionSpec \`${sol.slug}:${sol.version}\`, archetype \`${sol.archetype}\`.
- Deploys via the solution \`deploy/\` bundle (app stack ← agent stack alias ARN, threaded as a parameter — not ImportValue).
`;

  F['README.md'] = `# ${sol.name}\n\n${sol.description || ''}\n\nGenerated by AgentEye (dashboard-portal archetype). See **CLAUDE.md** for architecture and the remaining build tasks. Run with \`npm install && npm run dev\`.\n`;

  // ── enterprise deployment artifact pack ──────────────────────────────────────

  // Compute selectedSkills deterministically from spec config
  const selectedSkills = ['test-driven-development', 'code-review-and-quality'];
  const piiClass = app.data?.governance?.piiClassification;
  if ((piiClass && piiClass !== 'none' && piiClass !== 'review') || app.guardrails) {
    selectedSkills.push('security-and-hardening');
  }
  if (app.identity?.provider) selectedSkills.push('api-and-interface-design');
  selectedSkills.push('ci-cd-and-automation');
  selectedSkills.push('frontend-ui-engineering');
  // dedupe preserving order
  const seen = new Set();
  const skills = selectedSkills.filter(s => seen.has(s) ? false : (seen.add(s), true));

  const enterprise = app.enterprise || {};
  const cicd = enterprise.cicd || {};
  const tags = enterprise.tags || {};
  const dr = enterprise.dr || {};
  const envs = sol.environments || ['dev', 'stage', 'prod'];
  const iac = app.stack?.iac || enterprise.hosting?.iac || 'cloudformation';
  const dbEngine = app.stack?.database || 'aurora-serverless-pg';
  const primaryRegion = dr.primaryRegion || 'us-east-1';

  // helper: agent display name
  const agentName = a => a.agentName || a.name || a.slug || 'unknown';
  const agents = sol.agents || [];

  // 1. solution.manifest.json
  const manifestObj = {
    schemaVersion: '1.0',
    identity: {
      slug: sol.slug,
      name: sol.name,
      version: sol.version || null,
      archetype: sol.archetype,
    },
    dependencies: agents.map(a => ({
      agent: agentName(a),
      slug: a.slug || null,
      version: a.version || null,
      role: a.role || 'primary',
      binding: a.binding || 'bff',
      status: (a.slug && a.version) ? 'pinned' : 'target',
    })),
    stack: {
      ...(app.stack || {}),
      iac: iac,
    },
    theme: {
      palette: app.theme?.palette || 'accenture',
      mode: app.theme?.mode || 'light',
    },
    identityProvider: {
      provider: app.identity?.provider || null,
      rbacRoles: app.identity?.rbacRoles || [],
    },
    environments: envs,
    operations: {
      setup: 'make setup',
      build: 'make build',
      verify: 'make verify',
      deploy: 'make deploy ENV=<env>',
      smoke: 'make smoke ENV=<env>',
      teardown: 'make teardown ENV=<env>',
    },
    quality: {
      skills: skills,
      gate: ['install', 'build', 'typecheck', 'lint', 'test'],
    },
    provenance: {
      generator: 'appgen@0.1',
      blueprint: (sol.archetype || 'dashboard-portal') + '@0.1',
      model: null,
      generatedAt: new Date().toISOString(),
      spec: (sol.slug || 'unknown') + ':' + (sol.version || 'v000'),
    },
  };
  F['solution.manifest.json'] = JSON.stringify(manifestObj, null, 2) + '\n';

  // 2. Makefile (tab-indented recipes)
  F['Makefile'] = `# Makefile — lifecycle verbs for ${sol.name}
# Generated by AgentEye. All recipes call into the repo's npm scripts or
# the deploy/ bundle. Run \`make help\` to list targets.
#
# Prerequisites: Node >=18, AWS CLI v2, bash / git-bash on Windows.

SOLUTION ?= ${sol.slug || 'portal'}
REGION   ?= ${primaryRegion}
URL      ?=

.PHONY: help setup build verify deploy smoke teardown

help:
	@echo "Targets: setup | build | verify | deploy ENV=<dev|stage|prod> | smoke | teardown"

setup:
	npm install
	cp -n .env.example .env || true

build:
	npm run build

verify:
	npm run build
	@echo "Typecheck is part of the build (tsc -b). Add 'npm run lint' and 'npm test' once wired."

deploy:
	@test -n "$(ENV)" || (echo 'Usage: make deploy ENV=dev|stage|prod' && exit 1)
	@if [ -d deploy ]; then \\
	  cd deploy && ./deploy.sh $(SOLUTION)-$(ENV) $(REGION); \\
	else \\
	  echo 'No deploy/ bundle present — push the IaC artifacts first.'; \\
	fi

smoke:
	@if [ -z "$(URL)" ]; then echo 'Usage: make smoke URL=https://your-deployed-url'; exit 1; fi
	curl -fsS $(URL)/api/health

teardown:
	@echo "Teardown order: 1) app stack  2) BFF Lambda/APIGW  3) agent stacks"
	@echo "Run: aws cloudformation delete-stack --stack-name $(SOLUTION)-$(ENV) --region $(REGION)"
	@echo "Then delete agent CloudFormation stacks in reverse dependency order."
`;

  // 3. docs/ARCHITECTURE.md
  const agentTableRows = agents.map(a =>
    `| ${agentName(a)} | ${a.slug || '(target)'} | ${a.version || '(unpinned)'} | ${a.role || ''} | ${a.binding || 'bff'} | ${(a.slug && a.version) ? 'pinned' : 'target'} |`
  ).join('\n');
  F['docs/ARCHITECTURE.md'] = `# Architecture — ${sol.name}

## Tiers

| Tier | Technology | Hosting |
|------|-----------|---------|
| Frontend | React + Vite + TypeScript (${app.stack?.componentLib || 'shadcn-tailwind'}) | ${enterprise.hosting?.frontend || 'cloudfront-s3'} |
| BFF | Node HTTP (zero-dep) | ${enterprise.hosting?.bff || 'lambda-apigw'} |
| Database | ${dbEngine} | AWS-managed (same region) |
| IaC | ${iac} | ${enterprise.hosting?.iac || 'cloudformation'} |

## Agent Dependencies

| Agent | Slug | Version | Role | Binding | Status |
|-------|------|---------|------|---------|--------|
${agentTableRows || '| (none) | — | — | — | — | — |'}

## Data Flow

\`\`\`
Browser -> (HTTPS) -> CloudFront -> Frontend (S3)
                               \\ /api/* -> BFF (Lambda)
                                            | AGENT_ID / AGENT_ALIAS_ID
                                         Bedrock Agent Runtime
                                            | Action Groups / KB
                                         Agent Tools (DB, APIs, ...)
\`\`\`

## Trust Boundaries

- **BFF is the sole AWS caller.** The frontend never calls AWS APIs directly.
- **Secrets** (DB password, API keys) are stored as Secrets Manager ARN references; the BFF retrieves them at cold-start via IAM role — no secrets in env vars at rest.
- **Agent credentials** are scoped to the agent alias ARN; the BFF IAM role has \`bedrock:InvokeAgent\` on that specific ARN only.
- **Identity propagation**: ${app.identity?.propagateToAgent ? `Caller identity (\`${app.identity?.provider || 'provider'}\` JWT sub) is forwarded to the agent via \`sessionAttributes.callerIdentity\`.` : 'Identity is NOT propagated to the agent (set `propagateToAgent: true` in spec to enable).'}
- **Network**: ${enterprise.network?.mode || 'public'} mode — ${enterprise.network?.mode === 'vpcEndpoints' ? 'Bedrock and Secrets Manager accessed via VPC Endpoints; no NAT required.' : 'review network posture before production use.'}
`;

  // 4. docs/RUNBOOK.md
  F['docs/RUNBOOK.md'] = `# Runbook — ${sol.name}

## Lifecycle commands (via Makefile)

| Command | What it does |
|---------|-------------|
| \`make setup\` | \`npm install\` + create \`.env\` from \`.env.example\` |
| \`make build\` | \`npm run build\` (tsc + vite) |
| \`make verify\` | Hard gate: build must pass; extend with lint + test |
| \`make deploy ENV=dev\` | Run \`deploy/deploy.sh\` for the target environment |
| \`make smoke\` | \`curl\` the \`/api/health\` endpoint |
| \`make teardown ENV=dev\` | Guidance for ordered CloudFormation stack deletion |

## Deploy order

1. Deploy **agent CloudFormation stacks** first (one per agent dependency).
2. Note the \`AgentAliasArn\` output from each agent stack.
3. Populate \`deploy/parameters/<env>.json\` → \`agentAliasArn\`.
4. Deploy the **app stack** (BFF + frontend): \`make deploy ENV=<env>\`.
5. Run \`make smoke URL=<deployed-url>\` to confirm the health endpoint.

## Rollback

1. Re-deploy the previous app stack version (use the previous Git tag / release artifact).
2. If the agent was also updated, re-alias the agent to the prior version in Bedrock console or via AWS CLI.
3. Monitor CloudWatch alarms for 10 minutes after rollback.

## Observability

${enterprise.observability?.cloudwatchLogs ? '- **CloudWatch Logs**: BFF Lambda log group `/aws/lambda/' + (sol.slug || 'portal') + '-bff`.' : '- CloudWatch Logs: configure in enterprise settings.'}
${enterprise.observability?.xrayTracing ? '- **X-Ray**: tracing enabled on BFF Lambda — use Service Map to trace browser → BFF → agent.' : ''}
${enterprise.observability?.correlationIds ? '- **Correlation IDs**: BFF injects `x-correlation-id` on every agent call; appears in CloudWatch and X-Ray.' : ''}

## Common failures

| Symptom | Cause | Fix |
|---------|-------|-----|
| BFF returns stub reply | \`AGENT_ID\` / \`AGENT_ALIAS_ID\` not set | Populate from agent stack outputs → \`deploy/parameters/<env>.json\` |
| \`UnauthorizedException\` from Bedrock | BFF IAM role missing \`bedrock:InvokeAgent\` | Add \`bedrock:InvokeAgent\` on the alias ARN to the BFF execution role |
| Build fails: type error | TS strict mode catches a widget type mismatch | Fix the TypeScript error — do not relax \`strict\` |
| CloudFront 403 | S3 bucket policy out of sync with CloudFront OAC | Re-deploy app stack; bucket policy is managed by IaC |
`;

  // 5. docs/ENVIRONMENT-SETUP.md
  F['docs/ENVIRONMENT-SETUP.md'] = `# Environment Setup — ${sol.name}

## Prerequisites

| Tool | Min version | Purpose |
|------|-------------|---------|
| Node.js | 18 LTS | Build + BFF local run |
| npm | 9+ | Package management |
| AWS CLI | v2 | CloudFormation deploy + Secrets Manager |
| git | 2.40+ | Source control |

## AWS IAM — deploy role minimum permissions

The CI/CD role (or developer role) used by \`make deploy\` needs at minimum:
- \`cloudformation:*\` on the solution stacks
- \`s3:*\` on the frontend bucket
- \`lambda:*\` + \`apigateway:*\` on the BFF resources
- \`bedrock:InvokeAgent\` on the agent alias ARNs
- \`secretsmanager:GetSecretValue\` on the data source secrets
- \`iam:PassRole\` to the Lambda execution role

## Secrets

| Secret | Secrets Manager ARN | How it reaches the BFF |
|--------|--------------------|-----------------------|
| Agent ID / Alias | CFN parameter → Lambda env var \`AGENT_ID\` / \`AGENT_ALIAS_ID\` | Passed as CloudFormation parameter from agent stack output |
${(app.data?.sources || []).map(s => `| ${s.id} credentials | \`${s.secretRef || '<secretsmanager-arn>'}\` | BFF retrieves at cold-start via execution role |`).join('\n')}

## Per-environment configuration

Each environment has a parameter file under \`deploy/parameters/<env>.json\`:

\`\`\`
deploy/parameters/
  dev.json    ← DEV account / VPC coordinates + agent alias ARN
  stage.json  ← STAGE account / VPC coordinates + agent alias ARN
  prod.json   ← PROD account / VPC coordinates + agent alias ARN
\`\`\`

Populate \`agentAliasArn\` from the agent stack \`AgentAliasArn\` CloudFormation output
**before** running \`make deploy ENV=<env>\`.

## Region

Primary: \`${primaryRegion}\`${dr.secondaryRegion ? `  Secondary (DR): \`${dr.secondaryRegion}\`` : '  (single-region posture — no DR failover configured)'}

## Target environment constraints

Complete this section before deploying into a client landing zone:

- [ ] **Existing VPC + subnets** — VPC ID and private subnet IDs for BFF Lambda and DB
- [ ] **Permission boundary ARN** — if the client enforces an IAM permission boundary on all roles, add it to the CFN role definitions
- [ ] **Mandated tags** — confirm the tags in \`app.enterprise.tags\` satisfy the client's tag policy (current: ${Object.entries(tags).map(([k,v]) => `${k}=${v}`).join(', ') || '(none set)'})
- [ ] **SCP limits** — check for Service Control Policies that restrict Bedrock, Lambda, or S3 in the target account/OU
- [ ] **Network ACLs / Security Groups** — ensure BFF Lambda SG can reach Bedrock VPC Endpoint (if vpcEndpoints mode) and the DB subnet
- [ ] **KMS key** — customer-managed key ARN for ${enterprise.encryption?.mode || 'encryption'} (current: \`${enterprise.encryption?.kmsKeyArn || '<add-kms-arn>'}\`)
`;

  // 6. docs/THREAT-MODEL.md
  const hasPii = piiClass && piiClass !== 'none';
  F['docs/THREAT-MODEL.md'] = `# Threat Model — ${sol.name}

## Data classes

| Class | Detail |
|-------|--------|
| PII classification | ${piiClass || 'not set'} ${hasPii ? '⚠ PII present — apply encryption + audit logging' : ''} |
| Data residency | ${app.data?.governance?.residency || 'not set'} |
| Guardrails | ${app.guardrails ? JSON.stringify(app.guardrails) : 'none configured'} |

## STRIDE-lite

| Threat | Surface | Mitigation |
|--------|---------|-----------|
| **S**poofing | BFF ← browser (no auth header) | Implement ${app.identity?.provider || 'auth provider'} JWT verification in BFF; reject unsigned requests |
| **T**ampering | Agent session state | BFF validates \`sessionId\` format; agent action group inputs are schema-validated |
| **R**epudiation | Agent invocations | X-Ray + CloudWatch correlation IDs link every browser request to an agent invocation |
| **I**nformation disclosure | Secrets in logs | BFF must not log \`message\` content; CloudWatch log group KMS-encrypted |
| **D**enial of service | Bedrock RPM quota | Per-agent RPM limit enforced (${enterprise.quotas?.perAgentRpm || 'set in enterprise.quotas.perAgentRpm'}); implement BFF rate-limiting per user |
| **E**levation of privilege | RBAC bypass | BFF extracts roles from verified JWT; agent action groups must re-check role claim — do not trust client-supplied role header |

## Identity posture

- **Provider**: ${app.identity?.provider || '(none)'}
- **Roles**: ${(app.identity?.rbacRoles || []).join(', ') || '(none)'}
- **Identity propagated to agent**: ${app.identity?.propagateToAgent ? 'Yes — \`callerIdentity\` session attribute forwarded' : 'No'}

## Residency

Data residency requirement: **${app.data?.governance?.residency || 'not specified'}**.
The agent must be deployed in the same AWS region as the app stack (\`${primaryRegion}\`).
Cross-region agent calls violate this constraint.

## Guardrails summary

${app.guardrails ? `Bedrock Guardrails are configured: \`${JSON.stringify(app.guardrails)}\`. Ensure the guardrail ARN is threaded into the agent alias.` : 'No Bedrock Guardrails are configured in this spec. Evaluate whether content filtering is required before production, especially given PII classification: **' + (piiClass || 'not set') + '**.'}
`;

  // 7. docs/COST.md
  F['docs/COST.md'] = `# Cost Guide — ${sol.name}

## Resource cost map (rough order-of-magnitude)

| Resource | Billing model | Cost driver |
|----------|--------------|-------------|
| CloudFront + S3 (frontend) | Per-request + data transfer | Number of page loads; cache-hit rate |
| Lambda BFF (\`${enterprise.hosting?.bff || 'lambda-apigw'}\`) | Invocations + GB-seconds | Agent calls per user session |
| ${dbEngine} | ACU-hours (serverless) or instance-hours | Query volume; idle ACU minimum |
| Bedrock Agent Runtime | Per-token (input + output) | Model choice × conversation length |
| Secrets Manager | Per-secret per month + API calls | Negligible at this scale |
| CloudWatch Logs | Ingestion + storage | BFF log verbosity |

## Agent model cost note

The agent's model choice is the **primary cost lever**. Switching from a larger to a
smaller model can reduce per-invocation cost by 5–10×. Confirm the model selected in
the Bedrock agent configuration and set a monthly budget alarm in AWS Cost Explorer.

## Cost-allocation tags

The following tags are applied to all app and agent stack resources, enabling
per-solution cost tracking in Cost Explorer:

| Tag | Value |
|-----|-------|
${Object.entries(tags).map(([k, v]) => `| ${k} | ${v} |`).join('\n') || '| (no tags configured) | — |'}

Ensure the **agent CloudFormation stacks** apply the same tags (pass them as CFN
parameters) so agent and app costs roll up under the same cost-allocation keys.

## DR cost note

Posture: **${dr.posture || 'single-region'}**.${dr.secondaryRegion ? ` Secondary region \`${dr.secondaryRegion}\` incurs additional data-transfer and standby-resource costs.` : ' No secondary region — no additional DR spend.'}
`;

  // 8. docs/adr/0001-blessed-stack.md
  F['docs/adr/0001-blessed-stack.md'] = `# ADR 0001 — Blessed Stack Choice

**Date**: ${new Date().toISOString().slice(0, 10)}
**Status**: Accepted

## Context

AgentEye generates a deterministic application skeleton from a SolutionSpec.
A fixed "blessed" stack must be chosen once so the generator is deterministic
and the output is auditable across regenerations.

## Decision

Adopt the following golden-path stack for the \`dashboard-portal\` archetype:

| Layer | Choice | Rationale |
|-------|--------|-----------|
| Frontend | React + Vite + TypeScript | Broad ecosystem, fast HMR, TS strict mode for correctness |
| Component foundation | ${app.stack?.componentLib || 'shadcn-tailwind'} | Unstyled primitives + Tailwind — brand tokens stay in \`theme.css\` |
| BFF | Node HTTP (zero-dep) | Ships without bundler; cold-start under 50 ms on Lambda |
| Database | ${dbEngine} | Serverless autoscaling; IAM auth; Secrets Manager integration |
| IaC | ${iac} | Org-mandated; deterministic change-sets; no extra toolchain |
| Hosting (frontend) | ${enterprise.hosting?.frontend || 'cloudfront-s3'} | Global edge; no server-side rendering complexity |
| Hosting (BFF) | ${enterprise.hosting?.bff || 'lambda-apigw'} | Per-invocation billing; scales to zero |

## Consequences

**Positive**
- A single blessed stack means every AgentEye-generated repo is immediately
  familiar to any engineer who has worked on another one.
- IaC engine (\`${iac}\`) is already approved in the enterprise landing zone.
- Component library choice decouples brand tokens from component logic.

**Negative / trade-offs**
- Projects needing SSR (SEO-critical) cannot use this archetype as-is.
- Database choice (\`${dbEngine}\`) may not suit workloads needing strong OLAP.
- Switching the IaC engine later requires full stack re-deployment.
`;

  // 9. .github/workflows/deliver.yml
  const scans = cicd.scans || [];
  const scanSteps = [
    scans.includes('sbom')    && `      - name: SBOM\n        run: echo 'TODO: generate SBOM (e.g. syft . -o cyclonedx-json > sbom.json)'`,
    scans.includes('sca')     && `      - name: SCA (dependency scan)\n        run: echo 'TODO: run SCA tool (e.g. npm audit --audit-level=high)'`,
    scans.includes('sast')    && `      - name: SAST\n        run: echo 'TODO: run SAST tool (e.g. semgrep ci)'`,
    scans.includes('license') && `      - name: License check\n        run: echo 'TODO: run license checker (e.g. license-checker --onlyAllow MIT;ISC;Apache-2.0)'`,
  ].filter(Boolean).join('\n') || `      - name: Scans\n        run: echo 'No scans configured in spec — add sbom|sca|sast|license to enterprise.cicd.scans'`;
  F['.github/workflows/deliver.yml'] = `# CI/CD Pipeline — ${sol.name}
# Generated by AgentEye. Calls Makefile verbs where possible.
# Populate repository secrets: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY (or use OIDC).

name: deliver

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      env:
        description: 'Target environment'
        required: false
        default: 'dev'

env:
  AWS_REGION: ${primaryRegion}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: make setup
      - run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: make setup
      - run: make verify

  scan:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm install
${scanSteps}

  deploy-dev:
    needs: scan
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${primaryRegion}
      - run: make setup
      - run: make deploy ENV=dev

  deploy-stage:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${primaryRegion}
      - run: make setup
      - run: make deploy ENV=stage

  signoff:
    needs: deploy-stage
    runs-on: ubuntu-latest
    environment: prod-signoff${cicd.signOffGate ? '\n    # This environment requires a manual approval in GitHub Environments settings.' : ''}
    steps:
      - run: echo 'Sign-off gate passed — proceeding to production deploy.'

  deploy-prod:
    needs: signoff
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${primaryRegion}
      - run: make setup
      - run: make deploy ENV=prod

  smoke:
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke test
        run: |
          URL=\${{ vars.PROD_URL }}
          if [ -z "$URL" ]; then echo 'Set PROD_URL repo variable for smoke test'; exit 0; fi
          make smoke URL=$URL
      - name: Rollback note
        if: failure()
        run: echo 'Smoke failed — re-deploy previous release or roll back agent alias in Bedrock console.'
`;

  // 10. .claude/skills/README.md
  const skillDescriptions = {
    'test-driven-development':    'Enforces writing tests before implementation; drives widget data-binding and BFF route tests.',
    'code-review-and-quality':    'Code review checklist: type safety, no hardcoded secrets, consistent error handling, CSS token discipline.',
    'security-and-hardening':     'PII handling, input validation, least-privilege IAM, secret rotation, guardrail wiring.',
    'api-and-interface-design':   'JWT auth flow, BFF route contracts, OpenAPI-style interface between frontend and BFF.',
    'ci-cd-and-automation':       'Pipeline health, environment promotion gates, scan integration, rollback procedures.',
    'frontend-ui-engineering':    'React component patterns, Tailwind token discipline, accessibility (WCAG-AA), performance.',
  };
  F['.claude/skills/README.md'] = `# Claude Code Skills — ${sol.name}

These are **AgentEye-curated, vendored** engineering skills pre-selected for this
solution. They are referenced by \`CLAUDE.md\` and listed in
\`solution.manifest.json#quality.skills\`.

> **Vendored** means these skill identifiers are frozen at generation time.
> They are pointers to canonical AgentEye skill definitions — do not edit
> the identifiers; update the SolutionSpec and regenerate instead.

## Selected skills for this solution

${skills.map(s => `### \`${s}\`\n${skillDescriptions[s] || 'Engineering quality skill.'}`).join('\n\n')}

## How skills are activated

In Claude Code, skills are invoked via slash commands or referenced in CLAUDE.md
task descriptions. The skills above are pre-selected based on this solution's
configuration:

- Always included: \`test-driven-development\`, \`code-review-and-quality\`, \`ci-cd-and-automation\`, \`frontend-ui-engineering\`
${piiClass && piiClass !== 'none' && piiClass !== 'review' ? `- Added because \`piiClassification=${piiClass}\`: \`security-and-hardening\`` : app.guardrails ? '- Added because guardrails are configured: `security-and-hardening`' : ''}
${app.identity?.provider ? `- Added because \`identity.provider=${app.identity.provider}\`: \`api-and-interface-design\`` : ''}
`;

  // 11. deploy/parameters/<env>.json  (one per environment)
  for (const env of envs) {
    F[`deploy/parameters/${env}.json`] = JSON.stringify({
      account: '<ACCOUNT_ID>',
      region: primaryRegion,
      vpcId: enterprise.network?.vpcId || '',
      subnetIds: enterprise.network?.subnetIds || [],
      domain: '',
      agentAliasArn: '<from agent stack output AgentAliasArn>',
      tags: tags,
    }, null, 2) + '\n';
  }

  // ── S5: deterministic skeletons + typed contracts from the spec's rules/workflows ──
  // The soft/hard seam made concrete: each RULE → a JSON-schema contract + a deterministic
  // handler stub + a node:test `todo` stub; each WORKFLOW → a state-machine definition +
  // orchestrator stub. Bodies are bounded LLM fill (FILL-PLAN.md), governed by the baked-in
  // skills and proven by the verify gate. `todo` tests keep `npm test` GREEN until filled.
  const _slug = s => (String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 50) || 'item');
  const _camel = s => _slug(s).replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
  const _pascal = s => { const c = _camel(s); return c.charAt(0).toUpperCase() + c.slice(1); };
  const rules = app.rules || [];
  const workflows = app.workflows || [];

  rules.forEach(r => {
    const id = _slug(r.name || r.id);
    const binding = r.binding === 'action-group' ? 'action-group' : 'bff';
    const dir = binding === 'bff' ? 'bff/handlers' : 'agent/actions';
    F[`contracts/${id}.schema.json`] = JSON.stringify({
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      $id: `${id}.schema.json`, title: r.name || id, description: r.description || '',
      type: 'object', additionalProperties: false,
      properties: {
        input:  { type: 'object', description: 'TODO: define the rule inputs', additionalProperties: true },
        output: { type: 'object', description: 'TODO: define the rule outputs', additionalProperties: true },
      },
      required: ['input', 'output'],
    }, null, 2) + '\n';
    F[`${dir}/${id}.mjs`] = `// ${r.name || id} — DETERMINISTIC business rule (binding: ${binding}).
// Contract: contracts/${id}.schema.json   ·   Fill plan: docs/FILL-PLAN.md
// The agent PROPOSES calling this as a typed tool; this code ENFORCES the rule exactly.
// TODO (bounded fill, follow the test-driven-development + security-and-hardening skills):
//   ${(r.description || 'implement this rule').replace(/\n/g, ' ')}
export async function ${_camel(id)}(input) {
  // 1) validate \`input\` against contracts/${id}.schema.json
  // 2) implement the business logic (this is the auditable, deterministic path)
  // 3) return output matching the contract
  throw new Error('not implemented: ${id} (see docs/FILL-PLAN.md)');
}
`;
    F[`tests/${id}.test.mjs`] = `import { test } from 'node:test';
import assert from 'node:assert';
// import { ${_camel(id)} } from '../${dir}/${id}.mjs';
test('${id} — ${(r.description || '').replace(/'/g, '').replace(/\n/g, ' ').slice(0, 80)}', { todo: 'implement ${id} per its contract' }, async () => {
  assert.ok(true); // replace with real assertions against contracts/${id}.schema.json
});
`;
  });

  workflows.forEach(w => {
    const id = _slug(w.name || w.id);
    const steps = (w.steps || []).map((s, i) => ({ name: s.name || `step-${i + 1}`, kind: s.kind || 'deterministic' }));
    F[`workflows/${id}.workflow.json`] = JSON.stringify({
      name: w.name || id, description: w.description || '', trigger: w.trigger || 'manual',
      states: steps.map((s, i) => ({
        id: _slug(s.name), kind: s.kind, next: steps[i + 1] ? _slug(steps[i + 1].name) : null,
        approvalGate: s.kind === 'human-approval', agentInvoke: s.kind === 'agent',
      })),
    }, null, 2) + '\n';
    F[`workflows/${id}.mjs`] = `// ${w.name || id} — STATEFUL workflow orchestrator. Definition: workflows/${id}.workflow.json
// Steps: ${steps.map(s => `${s.name}[${s.kind}]`).join(' → ') || '(none captured)'}
// TODO (bounded fill): implement each state. Deterministic states are exact code; 'agent'
// states invoke the pinned agent through the BFF; 'human-approval' states MUST pause for sign-off.
export async function run${_pascal(id)}(ctx) {
  throw new Error('not implemented: ${id} (see docs/FILL-PLAN.md)');
}
`;
    F[`tests/${id}.workflow.test.mjs`] = `import { test } from 'node:test';
import assert from 'node:assert';
test('${id} workflow — states execute in order, approval gates pause', { todo: 'implement ${id}' }, async () => {
  assert.ok(true);
});
`;
  });

  if (rules.length || workflows.length) {
    const skillNote = 'Follow the vendored skills in `.claude/skills/` (test-driven-development, code-review-and-quality' + (rules.length ? ', security-and-hardening' : '') + '). Run `npm test` (node:test) — the stubs are `todo` and turn into real assertions as you fill them.';
    F['docs/FILL-PLAN.md'] = `# Bounded fill plan — ${sol.name}

This solution's **business logic** is split soft vs hard (see ARCHITECTURE.md): the agent *proposes*,
deterministic **rules** and stateful **workflows** *enforce*. The generator emitted typed contracts +
skeletons below; fill the bodies **within the contracts** — that's the only LLM-written part, and it
must pass \`make verify\` / \`npm test\`. ${skillNote}

## Rules (deterministic — \`contracts/*.schema.json\` + handlers)
${rules.length ? rules.map(r => { const id = _slug(r.name || r.id); const dir = (r.binding === 'action-group' ? 'agent/actions' : 'bff/handlers'); return `- **${r.name || id}** — ${r.description || ''}\n  - contract: \`contracts/${id}.schema.json\`  ·  handler: \`${dir}/${id}.mjs\`  ·  test: \`tests/${id}.test.mjs\``; }).join('\n') : '_(none captured)_'}

## Workflows (stateful — \`workflows/*.workflow.json\` + orchestrators)
${workflows.length ? workflows.map(w => { const id = _slug(w.name || w.id); return `- **${w.name || id}** — ${w.description || ''}\n  - definition: \`workflows/${id}.workflow.json\`  ·  orchestrator: \`workflows/${id}.mjs\`  ·  test: \`tests/${id}.workflow.test.mjs\`\n  - steps: ${(w.steps || []).map(s => `${s.name || '?'}[${s.kind || 'deterministic'}]`).join(' → ') || '(none)'}`; }).join('\n') : '_(none captured)_'}

> Each rule/workflow is a **typed tool** the agent calls — the contract is where soft meets hard.
> Human-approval workflow states must require a real sign-off before any irreversible action.
`;
    // make \`npm test\` runnable out of the box (node's built-in runner; zero deps)
    try { const pkg = JSON.parse(F['package.json']); pkg.scripts = pkg.scripts || {}; if (!pkg.scripts.test) pkg.scripts.test = 'node --test'; F['package.json'] = JSON.stringify(pkg, null, 2); } catch {}
    if (F['CLAUDE.md']) {
      F['CLAUDE.md'] += `\n## Business logic (bounded fill)\nThe deterministic **rules** (\`contracts/\` + \`bff/handlers\`|\`agent/actions\`) and **workflows** (\`workflows/\`) are scaffolded with typed contracts and \`todo\` tests. Fill the bodies per **docs/FILL-PLAN.md**, following the skills in \`.claude/skills/\`, until \`npm test\` is green. The agent never decides business-critical outcomes — it calls these as typed tools.\n`;
    }
  }

  return F;
}

// Re-parse the structural invariants every generated repo must hold. Throws.
function verifyRepo(F, sol) {
  JSON.parse(F['solution.manifest.json']);       // valid manifest
  JSON.parse(F['package.json']);                 // valid package.json
  JSON.parse(F['tsconfig.json']);                // valid tsconfig
  const pages = sol.app.pages || [];
  const widgetById = Object.fromEntries((sol.app.widgets || []).map(w => [w.id, w]));
  // every widget a page references exists, and its component is emitted
  for (const p of pages) for (const id of (p.widgets || [])) {
    const w = widgetById[id];
    if (!w) throw new Error(`page "${p.id}" references unknown widget "${id}"`);
    if (w.type === 'agent-chat') { if (!F['src/components/AgentChat.tsx']) throw new Error('agent-chat used but AgentChat not emitted'); continue; }
    const comp = WIDGET_COMPONENT[w.type];
    if (!comp) throw new Error(`widget "${id}" has unknown type "${w.type}"`);
    if (!F[`src/components/${comp}.tsx`]) throw new Error(`component ${comp} for widget "${id}" not emitted`);
  }
  // an agent-powered portal should pin at least one agent
  if (!(sol.agents || []).length) throw new Error('solution pins no agents (not agent-powered)');
}

function generateApp(solOrPath, outDir) {
  const sol = typeof solOrPath === 'string' ? JSON.parse(fs.readFileSync(solOrPath, 'utf8')) : solOrPath;
  if (sol.archetype !== 'dashboard-portal') throw new Error(`unsupported archetype "${sol.archetype}" (v1 = dashboard-portal)`);
  const F = buildFiles(sol);
  verifyRepo(F, sol);
  const root = outDir || path.join(__dirname, '..', 'generated', sol.slug || 'portal');
  // One-time-scaffold: overwrite only the files we generate; never wipe the
  // directory (preserves node_modules, .env, dist, and any hand edits).
  for (const [rel, content] of Object.entries(F)) {
    const dest = path.join(root, rel);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, content);
  }
  return { root, fileCount: Object.keys(F).length };
}

function main() {
  const [solPath, outDir] = process.argv.slice(2);
  if (!solPath) { console.error('usage: node appgen/generate.js <solution.json> [outDir]'); process.exit(2); }
  const { root, fileCount } = generateApp(solPath, outDir);
  console.log(`✓ generated ${fileCount} files → ${path.relative(path.join(__dirname, '..'), root)}/`);
}

if (require.main === module) main();
module.exports = { generateApp, buildFiles, verifyRepo };
