// cfn/agent-cfn.js
// Deterministic compiler: AgentEye agent config (meta.json `agent` block) → AWS
// CloudFormation YAML. NO model call — same input yields byte-identical output,
// so it's reproducible and lintable in CI (cfn-lint).
//
// Phase 1 scope: specialist & supervisor agents WITHOUT knowledge bases, action
// groups, or MCP connectors. Those are emitted as a Metadata note (transparent
// skip), not silently dropped. KB/action-group resources land in Phase 2.
//
// Everything account/region-specific (model id, KMS key, collaborator alias
// ARNs) becomes a CFN Parameter with a default, so a stale default can be
// overridden at deploy time without regenerating the template.

'use strict';

const yaml = require('js-yaml');

// ── Friendly model name → Bedrock model/inference-profile id ─────────────────
// NOTE: newer Claude models require a cross-region INFERENCE PROFILE id (the
// `us.` prefix) for on-demand throughput, not the raw foundation-model id.
// These are best-known defaults and are emitted as a Parameter DEFAULT — verify
// against the models enabled in your target region, or override at deploy time.
const MODEL_MAP = {
  'claude-opus-4-7':   'us.anthropic.claude-opus-4-20250514-v1:0',
  'claude-opus-4':     'us.anthropic.claude-opus-4-20250514-v1:0',
  'claude-sonnet-4-6': 'us.anthropic.claude-sonnet-4-20250514-v1:0',
  'claude-sonnet-4':   'us.anthropic.claude-sonnet-4-20250514-v1:0',
  'claude-haiku-4-5':  'us.anthropic.claude-haiku-4-5-20251001-v1:0',
};
const DEFAULT_MODEL_ID = 'us.anthropic.claude-sonnet-4-20250514-v1:0';

function modelIdFor(friendly) {
  if (!friendly) return DEFAULT_MODEL_ID;
  const key = String(friendly).toLowerCase().trim();
  return MODEL_MAP[key] || DEFAULT_MODEL_ID;
}

// ── small helpers ────────────────────────────────────────────────────────────
const Ref    = name        => ({ Ref: name });
const GetAtt = (res, attr) => ({ 'Fn::GetAtt': [res, attr] });
const Sub    = tmpl        => ({ 'Fn::Sub': tmpl });

// CFN logical IDs must be alphanumeric. PascalCase a slug/name.
function logicalId(s) {
  return String(s || '')
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .split(' ').filter(Boolean)
    .map(w => w[0].toUpperCase() + w.slice(1))
    .join('') || 'X';
}

// Bedrock guardrail topic Name allows [0-9a-zA-Z-_ !?.], <=100 chars.
function topicName(s, i) {
  const cleaned = String(s || '').replace(/[^0-9a-zA-Z\-_ !?.]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 100);
  return cleaned || `DeniedTopic${i + 1}`;
}

const CONTENT_FILTER_TYPE = { harmful: 'MISCONDUCT', hateful: 'HATE', sexual: 'SEXUAL', violent: 'VIOLENCE' };
const PII_ENTITY_TYPES = ['NAME', 'EMAIL', 'PHONE', 'ADDRESS', 'AGE', 'US_SOCIAL_SECURITY_NUMBER', 'CREDIT_DEBIT_CARD_NUMBER', 'PASSWORD'];

function tagMap(tags) {
  const out = {};
  Object.entries(tags || {}).forEach(([k, v]) => { if (v != null && v !== '') out[k] = String(v); });
  return out;
}
const tagList = tags => Object.entries(tagMap(tags)).map(([Key, Value]) => ({ Key, Value }));

// ── guardrail resources ──────────────────────────────────────────────────────
function buildGuardrail(g, tags) {
  const props = {
    Name: Sub('${AWS::StackName}-guardrail'),
    Description: 'Generated by AgentEye from agent guardrail config.',
    BlockedInputMessaging:   'This request can\'t be processed due to content policy.',
    BlockedOutputsMessaging: 'The response was withheld due to content policy.',
  };

  const filters = Object.entries(g.contentFilters || {})
    .filter(([, on]) => on)
    .map(([k]) => CONTENT_FILTER_TYPE[k])
    .filter(Boolean)
    .map(Type => ({ Type, InputStrength: 'HIGH', OutputStrength: 'HIGH' }));
  // PROMPT_ATTACK must have OutputStrength NONE per Bedrock.
  filters.push({ Type: 'PROMPT_ATTACK', InputStrength: 'HIGH', OutputStrength: 'NONE' });
  props.ContentPolicyConfig = { FiltersConfig: filters };

  const pii = g.piiHandling || g.phiHandling;
  if (pii) {
    const Action = pii === 'block' ? 'BLOCK' : 'ANONYMIZE';
    props.SensitiveInformationPolicyConfig = {
      PiiEntitiesConfig: PII_ENTITY_TYPES.map(Type => ({ Type, Action })),
    };
  }

  if (Array.isArray(g.deniedTopics) && g.deniedTopics.length) {
    props.TopicPolicyConfig = {
      TopicsConfig: g.deniedTopics.map((t, i) => ({
        Name: topicName(t, i), Definition: String(t).slice(0, 200), Type: 'DENY',
      })),
    };
  }

  const tl = tagList(tags);
  if (tl.length) props.Tags = tl;
  return { Type: 'AWS::Bedrock::Guardrail', Properties: props };
}

// ── main compiler ──────────────────────────────────────────────────────────
function buildAgentCfn(agent, opts = {}) {
  if (!agent || !agent.name) throw new Error('agent.name required');

  const a = agent;
  const isSupervisor = a.agentMode === 'supervisor';
  const ent = a.enterprise || {};
  const tags = ent.tags || {};
  const hasGuardrail = !!a.guardrails;
  const customerKms = ent.encryption && ent.encryption.mode === 'customer-managed';
  const collaborators = isSupervisor ? (a.collaborators || []) : [];

  const skipped = [];
  if ((a.knowledgeBases || []).length) skipped.push(`${a.knowledgeBases.length} knowledge base(s)`);
  if ((a.actionGroups   || []).length) skipped.push(`${a.actionGroups.length} action group(s)`);
  if ((a.mcpConnectors  || []).length) skipped.push(`${a.mcpConnectors.length} MCP connector(s)`);

  const Parameters = {};
  const Resources  = {};
  const Outputs     = {};

  // ── Parameters (account/region specifics, overridable at deploy) ──
  Parameters.FoundationModelId = {
    Type: 'String',
    Default: modelIdFor(a.foundationModel),
    Description: `Bedrock model / inference-profile id (mapped from "${a.foundationModel || 'default'}"). Verify it is enabled in your region; override if needed.`,
  };
  if (customerKms) {
    Parameters.CustomerKmsKeyArn = {
      Type: 'String',
      Default: (ent.encryption && ent.encryption.kmsKeyArn) || '',
      Description: 'Customer-managed KMS key ARN for agent encryption.',
    };
  }
  const collabParam = {};
  collaborators.forEach(c => {
    const pid = `Collaborator${logicalId(c.agentName)}AliasArn`;
    collabParam[c.agentName] = pid;
    Parameters[pid] = {
      Type: 'String',
      Description: `Agent alias ARN for collaborator "${c.agentName}" (pinned ${c.agentId || 'n/a'}). Output of that agent's stack.`,
    };
  });

  // ── IAM execution role ──
  const rolePolicyStatements = [{
    Sid: 'InvokeModel',
    Effect: 'Allow',
    Action: ['bedrock:InvokeModel', 'bedrock:InvokeModelWithResponseStream'],
    Resource: [
      Sub('arn:aws:bedrock:*::foundation-model/*'),
      Sub('arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/*'),
    ],
  }];
  if (hasGuardrail) {
    rolePolicyStatements.push({
      Sid: 'ApplyGuardrail', Effect: 'Allow',
      Action: ['bedrock:ApplyGuardrail'], Resource: GetAtt('Guardrail', 'GuardrailArn'),
    });
  }
  if (collaborators.length) {
    rolePolicyStatements.push({
      Sid: 'InvokeCollaborators', Effect: 'Allow',
      Action: ['bedrock:InvokeAgent', 'bedrock:GetAgentAlias'],
      Resource: collaborators.map(c => Ref(collabParam[c.agentName])),
    });
  }
  Resources.AgentExecutionRole = {
    Type: 'AWS::IAM::Role',
    Properties: {
      AssumeRolePolicyDocument: {
        Version: '2012-10-17',
        Statement: [{
          Effect: 'Allow',
          Principal: { Service: 'bedrock.amazonaws.com' },
          Action: 'sts:AssumeRole',
          Condition: { StringEquals: { 'aws:SourceAccount': Ref('AWS::AccountId') } },
        }],
      },
      Policies: [{ PolicyName: 'AgentInvokePolicy', PolicyDocument: { Version: '2012-10-17', Statement: rolePolicyStatements } }],
      Tags: tagList(tags),
    },
  };

  // ── Guardrail (+ version) ──
  if (hasGuardrail) {
    Resources.Guardrail = buildGuardrail(a.guardrails, tags);
    Resources.GuardrailVersion = {
      Type: 'AWS::Bedrock::GuardrailVersion',
      Properties: { GuardrailIdentifier: GetAtt('Guardrail', 'GuardrailId'), Description: 'Published by AgentEye.' },
    };
  }

  // ── Agent ──
  const agentProps = {
    AgentName: Sub('${AWS::StackName}-agent'),
    FoundationModel: Ref('FoundationModelId'),
    Instruction: a.instruction || `You are ${a.name}.`,
    AgentResourceRoleArn: GetAtt('AgentExecutionRole', 'Arn'),
    AutoPrepare: true,
    IdleSessionTTLInSeconds: 1800,
  };
  if (a.description) agentProps.Description = a.description;
  if (customerKms) agentProps.CustomerEncryptionKeyArn = Ref('CustomerKmsKeyArn');
  if (hasGuardrail) {
    agentProps.GuardrailConfiguration = {
      GuardrailIdentifier: GetAtt('Guardrail', 'GuardrailId'),
      GuardrailVersion: GetAtt('GuardrailVersion', 'Version'),
    };
  }
  const mem = a.memory || {};
  if (mem.sessionMemory || mem.type === 'session-summary' || mem.sessionSummary) {
    agentProps.MemoryConfiguration = {
      EnabledMemoryTypes: ['SESSION_SUMMARY'],
      StorageDays: mem.retentionDays || mem.storageDays || 30,
    };
  }
  if (isSupervisor) {
    agentProps.AgentCollaboration = 'SUPERVISOR';
    if (collaborators.length) {
      agentProps.AgentCollaborators = collaborators.map(c => ({
        CollaboratorName: logicalId(c.agentName),
        AgentDescriptor: { AliasArn: Ref(collabParam[c.agentName]) },
        CollaborationInstruction: c.routingRule || `Delegate to ${c.agentName} when relevant.`,
        RelayConversationHistory: 'TO_COLLABORATOR',
      }));
    }
  }
  const agentTagMap = tagMap(tags);
  if (Object.keys(agentTagMap).length) agentProps.Tags = agentTagMap;
  Resources.Agent = { Type: 'AWS::Bedrock::Agent', Properties: agentProps };

  // ── Alias (deploy handle) ──
  Resources.AgentAlias = {
    Type: 'AWS::Bedrock::AgentAlias',
    Properties: {
      AgentId: GetAtt('Agent', 'AgentId'),
      AgentAliasName: 'live',
      ...(Object.keys(agentTagMap).length ? { Tags: agentTagMap } : {}),
    },
  };

  // ── Outputs (the fusion surface: app/supervisor stacks consume these) ──
  const exp = suffix => ({ 'Fn::Sub': '${AWS::StackName}-' + suffix });
  Outputs.AgentId       = { Value: GetAtt('Agent', 'AgentId'),          Export: { Name: exp('AgentId') } };
  Outputs.AgentArn      = { Value: GetAtt('Agent', 'AgentArn'),         Export: { Name: exp('AgentArn') } };
  Outputs.AgentAliasId  = { Value: GetAtt('AgentAlias', 'AgentAliasId'),Export: { Name: exp('AgentAliasId') } };
  Outputs.AgentAliasArn = { Value: GetAtt('AgentAlias', 'AgentAliasArn'),Export: { Name: exp('AgentAliasArn') } };

  const template = {
    AWSTemplateFormatVersion: '2010-09-09',
    Description: `AgentEye-generated Bedrock ${isSupervisor ? 'supervisor' : 'specialist'} agent: ${a.name}`,
    Metadata: {
      'AgentEye::Provenance': {
        generator: 'agent-cfn@0.1',
        agentName: a.name,
        agentMode: a.agentMode || 'specialist',
        foundationModel: a.foundationModel || null,
        phase1ScopeNote: skipped.length
          ? `Phase-1 template omits (deferred to Phase 2): ${skipped.join(', ')}.`
          : 'No KB / action groups / MCP connectors on this agent.',
      },
    },
    Parameters,
    Resources,
    Outputs,
  };

  return yaml.dump(template, { lineWidth: -1, noRefs: true, sortKeys: false });
}

module.exports = { buildAgentCfn, modelIdFor, MODEL_MAP, DEFAULT_MODEL_ID, logicalId };
