#!/usr/bin/env node
// cfn/solution-deploy.js — build a solution-level deploy/ bundle: the pinned
// agent closure(s) PLUS the app stack, deployed leaves-first. The primary
// agent stack's AgentId / AgentAliasId / AgentAliasArn outputs are threaded into
// the app stack's parameters (params, not ImportValue) — closing the app→agent
// edge with the exact pattern proven for agent→agent.
//
//   node cfn/solution-deploy.js <solution.json> [outDir]

'use strict';

const fs   = require('fs');
const path = require('path');
const { resolveClosure, renderDeployScript, verifyBundle } = require('./deploy-manifest');
const { logicalId } = require('./agent-cfn');
const { buildAppCfn } = require('./app-cfn');

const LIBRARY_DIR = path.join(__dirname, '..', 'library');

function buildSolutionDeploy(solOrPath, outDir) {
  const sol = typeof solOrPath === 'string' ? JSON.parse(fs.readFileSync(solOrPath, 'utf8')) : solOrPath;
  if (sol.archetype !== 'dashboard-portal') throw new Error(`unsupported archetype "${sol.archetype}"`);
  const pinned = sol.agents || [];
  if (!pinned.length) throw new Error('solution pins no agents');
  const primary = pinned.find(a => a.role === 'primary') || pinned[0];

  // Resolve the closure of every pinned agent; merge (dedupe by key, preserve leaves-first order).
  const nodes = {};
  const order = [];
  for (const a of pinned) {
    const { nodes: n, order: o } = resolveClosure(a.slug, a.version);
    Object.assign(nodes, n);
    for (const k of o) if (!order.includes(k)) order.push(k);
  }

  const outRoot = outDir || path.join(__dirname, '..', 'generated', sol.slug || 'solution');
  const deployDir = path.join(outRoot, 'deploy');
  const templateDir = path.join(deployDir, 'templates');
  fs.rmSync(deployDir, { recursive: true, force: true });
  fs.mkdirSync(templateDir, { recursive: true });

  // Agent stacks (copied from the Library) — same collaborator param wiring as the agent bundle.
  const stacks = order.map(key => {
    const n = nodes[key];
    const src = path.join(LIBRARY_DIR, n.slug, n.version, 'agent.cfn.yaml');
    if (!fs.existsSync(src)) throw new Error(`missing ${n.slug}/${n.version}/agent.cfn.yaml — run \`npm run cfn:backfill\``);
    const tf = `${n.slug}__${n.version}.yaml`;
    fs.copyFileSync(src, path.join(templateDir, tf));
    return {
      name: n.slug, slug: n.slug, version: n.version, role: key === `${primary.slug}:${primary.version}` ? 'primary-agent' : 'agent',
      template: `templates/${tf}`,
      dependsOn: n.collaborators.map(c => nodes[c.key].slug),
      params: n.collaborators.map(c => ({ name: `Collaborator${logicalId(c.name)}AliasArn`, fromStackOutput: { stack: nodes[c.key].slug, output: 'AgentAliasArn' } })),
    };
  });

  // App stack (generated fresh from the spec), wired to the PRIMARY agent stack.
  fs.writeFileSync(path.join(templateDir, 'app.yaml'), buildAppCfn(sol));
  const appName = `${sol.slug}-app`;
  stacks.push({
    name: appName, slug: sol.slug, version: sol.version, role: 'app',
    template: 'templates/app.yaml',
    dependsOn: [primary.slug],
    params: [
      { name: 'AgentId',       fromStackOutput: { stack: primary.slug, output: 'AgentId' } },
      { name: 'AgentAliasId',  fromStackOutput: { stack: primary.slug, output: 'AgentAliasId' } },
      { name: 'AgentAliasArn', fromStackOutput: { stack: primary.slug, output: 'AgentAliasArn' } },
      { name: 'BffCodeBucket', fromEnv: 'BFF_CODE_BUCKET' },
      { name: 'BffCodeKey',    fromEnv: 'BFF_CODE_KEY' },
    ],
  });

  const manifest = {
    solution: sol.slug, rootVersion: sol.version, generator: 'solution-deploy@0.1',
    capabilities: ['CAPABILITY_IAM'], finalOutput: 'SiteUrl',
    deployOrder: stacks.map(s => s.name), stacks,
  };
  fs.writeFileSync(path.join(deployDir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  fs.writeFileSync(path.join(deployDir, 'deploy.sh'), renderDeployScript(manifest));
  fs.writeFileSync(path.join(deployDir, 'README.md'), renderReadme(manifest, sol));

  verifyBundle(deployDir);   // throws on any wiring inconsistency
  return { deployDir, manifest };
}

function renderReadme(m, sol) {
  return `# Solution deploy bundle — ${sol.name || m.solution}

Deploys the full solution as one ordered set of CloudFormation stacks: the pinned
agent(s) and their collaborators, then the app tier. Generated by \`${m.generator}\`.

## Deploy order (leaves first)
${m.deployOrder.map((s, i) => `${i + 1}. ${s}`).join('\n')}

The app stack's \`AgentId\` / \`AgentAliasId\` / \`AgentAliasArn\` parameters are filled
from the primary agent stack's outputs at deploy time (params, not \`ImportValue\`).

## Prerequisites
- AWS CLI v2, authenticated to the target account.
- The BFF deployment package uploaded to S3; export its location:
  \`\`\`bash
  export BFF_CODE_BUCKET=my-artifacts-bucket
  export BFF_CODE_KEY=patientportal/bff.zip
  \`\`\`
- The frontend build (\`npm run build\`) synced to the FrontendBucket output after deploy.

## Run
\`\`\`bash
./deploy.sh <stack-name-prefix> <region>
\`\`\`

## Teardown (reverse order)
\`\`\`bash
${[...m.deployOrder].reverse().map(s => `aws cloudformation delete-stack --stack-name <prefix>-${s} --region <region>`).join('\n')}
\`\`\`
`;
}

function main() {
  const [solPath, outDir] = process.argv.slice(2);
  if (!solPath) { console.error('usage: node cfn/solution-deploy.js <solution.json> [outDir]'); process.exit(2); }
  const { deployDir, manifest } = buildSolutionDeploy(solPath, outDir);
  console.log(`✓ wrote ${path.relative(path.join(__dirname, '..'), deployDir)}/`);
  console.log(`  deploy order: ${manifest.deployOrder.join(' → ')}`);
}

if (require.main === module) main();
module.exports = { buildSolutionDeploy };
